/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PlanningRouteImport } from './routes/planning'
import { Route as NetWorthRouteImport } from './routes/net-worth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as BankCallbackRouteImport } from './routes/bank-callback'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanningRoute = PlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => rootRouteImport,
} as any)
const NetWorthRoute = NetWorthRouteImport.update({
  id: '/net-worth',
  path: '/net-worth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const BankCallbackRoute = BankCallbackRouteImport.update({
  id: '/bank-callback',
  path: '/bank-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/bank-callback': typeof BankCallbackRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/net-worth': typeof NetWorthRoute
  '/planning': typeof PlanningRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/bank-callback': typeof BankCallbackRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/net-worth': typeof NetWorthRoute
  '/planning': typeof PlanningRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/bank-callback': typeof BankCallbackRoute
  '/expenses': typeof ExpensesRoute
  '/login': typeof LoginRoute
  '/net-worth': typeof NetWorthRoute
  '/planning': typeof PlanningRoute
  '/portfolio': typeof PortfolioRoute
  '/settings': typeof SettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/bank-callback'
    | '/expenses'
    | '/login'
    | '/net-worth'
    | '/planning'
    | '/portfolio'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/bank-callback'
    | '/expenses'
    | '/login'
    | '/net-worth'
    | '/planning'
    | '/portfolio'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/bank-callback'
    | '/expenses'
    | '/login'
    | '/net-worth'
    | '/planning'
    | '/portfolio'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  BankCallbackRoute: typeof BankCallbackRoute
  ExpensesRoute: typeof ExpensesRoute
  LoginRoute: typeof LoginRoute
  NetWorthRoute: typeof NetWorthRoute
  PlanningRoute: typeof PlanningRoute
  PortfolioRoute: typeof PortfolioRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planning': {
      id: '/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof PlanningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/net-worth': {
      id: '/net-worth'
      path: '/net-worth'
      fullPath: '/net-worth'
      preLoaderRoute: typeof NetWorthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank-callback': {
      id: '/bank-callback'
      path: '/bank-callback'
      fullPath: '/bank-callback'
      preLoaderRoute: typeof BankCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  BankCallbackRoute: BankCallbackRoute,
  ExpensesRoute: ExpensesRoute,
  LoginRoute: LoginRoute,
  NetWorthRoute: NetWorthRoute,
  PlanningRoute: PlanningRoute,
  PortfolioRoute: PortfolioRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
